services:
  - type: web
    name: onpoint-amenities-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: ATTIO_API_KEY
        sync: false
